USE voting_system;

-- Job and organization tables
CREATE TABLE JobCategories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Fields (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category_id INT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES JobCategories(id) ON DELETE CASCADE
);

CREATE TABLE Jobs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    field_id INT NOT NULL,
    FOREIGN KEY (field_id) REFERENCES Fields(id) ON DELETE CASCADE
);

CREATE TABLE Sectors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Organizations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    sector_id INT NOT NULL,
    FOREIGN KEY (sector_id) REFERENCES Sectors(id) ON DELETE CASCADE
);
select 'job  ok';